export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS';
export const LOAD_DATA = 'LOAD_DATA';
export const LOAD_DATA_FAILURE = 'LOAD_DATA_FAILURE';
export const ACTION_FIND_MESSAGE = 'ACTION_FIND_MESSAGE';
export const ACTION_DELETE_MESSAGE = 'ACTION_DELETE_MESSAGE';
